# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        run: |
         pip3 install --upgrade pip setuptools wheel
         pip3 install psutil
         pip3 install matplotlib
         pip3 install numpy
         pip3 install pandas
         pip3 install keras
         pip3 install sklearn
      
      - name: Run script
        run: python3 2-id3-svm-lib.py

      
